### ISSUE TITLE
Doesn't use original filenames

### ISSUE THREAD

**Issue by MlCHEL1234** [jscher2000/Save-webP-as-extension#13]
The addon (for firefox for Linux) doesn't use the original-filenames for saving, but uses (example) "**unnamed_file_from_www.rockcrawler.de.jpg_[www.rockcrawler.de].jpg**" . The original-filename is displayed in the first line of the "Save webP as PNG or JPEG"-window/requester, so why don't use the correct name for saving?

**Comment by jscher2000** [comment]
Can you give a link to the problem page and describe which image it is, or provide the direct link to the image? The code to extract the file name may not be working for that image's URL.

**Comment by MlCHEL1234** [comment]
Hi,

i sent You some via email, but maybe they didn't find the right way... So here are some more from a rc-car-forum, only examples, because this happens on many other sources too.

1.) adress:    https://www.rockcrawler.de/wcf/attachment/1277523-img-20220914-185218-jpg/
2.) should be:   IMG_20220914_185218
3.) is:   unnamed_file_from_www.rockcrawler.de.jpg_[www.rockcrawler.de].jpg

1.) https://www.rockcrawler.de/wcf/attachment/1277527-img-20220914-192210-jpg/
2.) IMG_20220914_192210
3:) the same as above

1.) https://www.rockcrawler.de/wcf/attachment/1277249-517d2fcc-2530-4837-8853-02040a7d887d-jpg/
2.) 517D2FCC-2530-4837-8853-02040A7D887D
3.) is:   unnamed_file_from_www.rockcrawler.de.jpg_[www.rockcrawler.de].jpg

webp has the ability to also show animated pics (like 'gif'), but in Your firefox-addon there is nothing to save webp as gif. Could this be added?

**Comment by jscher2000** [comment]
Thank you for the links. I will study those (hopefully this weekend).

For animated GIFs, try the IE11 button to see whether that triggers the server to send an alternate format.

**Comment by jscher2000** [comment]
In the stand-alone image viewer, the site's preferred file name is part of the title (along with format, dimensions, and whether the image is currently scaled). Version 1.3 extracts that file name. Hopefully correctly! You can update and let me know how it works for you.

**Comment by MlCHEL1234** [comment]
Hi, thanks for your response.

I doesn't work till now. Here you can find two screenshots.

https://highlaender.bplaced.net/michelsburg/diesunddas/divers/FFAddon01.jpg
https://highlaender.bplaced.net/michelsburg/diesunddas/divers/FFAddon02.jpg

One shows the problem with the two file-requesters added via gimp (Addon-Requester and Firefox-Requester).

You see the original-picture in the background and the selection-window of your addon and of Firefox. You see, that the Firefox-SaveAs-Requester has the correkt filename, while the addon-Requester doesn't have the original filename.

In the other screenshot you see my preferences of the addon in firefox about:addons

May be this helps a little. I don't think, that i have a configuration-problem, as on other websites the addon works fine. This website is from my main-hobby and so important for me. Perhaps you can eliminate this problem...

Bye
Michael

Excuse, if my English is "suboptimal", English isn't my motherlanguage.

**Comment by jscher2000** [comment]
This is why I need to completely rewrite this extension: I have three different sets of file naming code, and because I turned off automatic display of the bar, I forgot to test this one. Hopefully it will work for you now in version 1.3.2.

**Comment by MlCHEL1234** [comment]
Hello,
now it works. Very fine. Thank You very much for the fast and successful support. Very good work!!!
Bye
Michael
