### ISSUE TITLE
I can no longer save images using the extension.

### ISSUE THREAD

**Issue by LautaroL20** [jscher2000/Save-webP-as-extension#16]
The extension was working fine, but suddenly it no longer allows me to save images, because when I try to save any, this is what happens:

`Apologies, but the quick save didn't work. Firefox says: 'Error: docct is not defined'`

Here is a gif showing the issue: 

![GIF](https://user-images.githubusercontent.com/12244376/190900405-42e3e9e9-2f61-487c-ba0f-f1ceadcb5ad9.gif)

**Comment by jscher2000** [comment]
Really sorry about that, I didn't test the Quick Save configuration. Should be fixed in version 1.3.1 (just uploaded).
