### ISSUE TITLE
"Open bar automatically on stand-alone web images" option does open for non webP images

### ISSUE THREAD

**Issue by syldub69** [jscher2000/Save-webP-as-extension#2]
Hi,
When the "Open bar automatically on stand-alone web images" option is enabld, the bar is opened for non webP images as well, like JPG images.
I think it will be better if the bar opens automatically only for webP images.

**Comment by jscher2000** [comment]
That's an interesting idea. Let me look into it. Sorry I didn't catch this before today's update!

It's probably more important now that I added an Image Info panel to the bar that opens with the stand-alone image. Takes up quite a bit of space...

**Comment by jscher2000** [comment]
Version 0.9.1 has a checkbox for this on the Options panel. Let me know whether it works the way you wanted.

**Comment by syldub69** [comment]
Now, when I check the new option "image/webp only", the panel is no more displayed for stand-alone JPG images.
But it is not displayed for some stand-alone webp image. For example:
https://images.philips.com/is/image/philipsconsumer/74792629dee648d9ae67ac5b009813da?$jpglarge$&wid=960
The Image Info panel is a good idea. Maybe just decrease the font size a little bit ?

**Comment by jscher2000** [comment]
Okay, yes, I see the problem. I thought it would be more efficient to look at this earlier but it's in the wrong context. Will need to patch in coming days.

**Comment by jscher2000** [comment]
I think this should be fixed in version 0.9.4. Please let me know if the problem continues.

**Comment by syldub69** [comment]
Seems to work like a charm ! Thanks !
