### ISSUE TITLE
An error message is displayed if the saving process is canceled.

### ISSUE THREAD

**Issue by LautaroL20** [jscher2000/Save-webP-as-extension#20]
![Image](https://user-images.githubusercontent.com/12244376/235000285-1d4a15a8-ec02-4e94-80ac-c883a696274e.png)

**Steps to reproduce the problem:**

**1. Right-click on an image.
2. Click on "Save webP as..".
3. Once the "save as" window opens, click on "Cancel", or on the "X" button.
4. The error message should be displayed.**

**Comment by jscher2000** [comment]
I'm sorry, this was added a little while ago to try to track down a problem. I didn't realize it would appear when the user canceled the Save As dialog (I didn't test that because I auto-save the images). Let me see whether I can distinguish between the two cases.

**Comment by LautaroL20** [comment]
Hello sir, this error happens to me very often and it's starting to get a bit annoying, so I was wondering if you could push a small fix for it when you have the time?

**Comment by jscher2000** [comment]
I apologize for the delay. I uploaded version 1.3.5 with a fix for this, but it probably will be a day or two before it is approved and becomes available for installation.

**Comment by jscher2000** [comment]
Should be updating automatically, or on the Add-ons page, click the gear button to the upper right of your extensions list and Check for Updates.
