### ISSUE TITLE
Auto-open settings not functional

### ISSUE THREAD

**Issue by Hexerin** [jscher2000/Save-webP-as-extension#26]
![593ec3c67384e3691823829cb2584bc1](https://github.com/jscher2000/Save-webP-as-extension/assets/42397404/1f7e4bf0-6ef4-47bc-aca3-9a7501ef4a57)

These settings aren't working. No matter what combo of these I set, the plugin automatically opens the overlay on every image regardless.

![d8492f78e6347ade89dc97cf59e28082](https://github.com/jscher2000/Save-webP-as-extension/assets/42397404/ae2b8319-e568-4173-adcd-d1859a19ec3f)

The auto-close setting does work, however.

**Comment by jscher2000** [comment]
I can't think of a logical reason for that. One possibility is that the add-on preference storage somehow got corrupted so what you see on the Options page is not really what is stored. Maybe. 

You can clear the add-on preference storage this way:

(1) Open about:debugging and in the left column, click This Firefox

(2) Find this add-on and click the Inspect button

(3) In the pop-up debugging console, switch to the Storage tab and expand Extension Storage

(4) Right-click `prefs` and delete it -- after that, you might need to disable and re-enable the extension to flush it from memory (I'm not sure how long it is retained in memory)

![Extension-debugger-Storage-context-menu](https://github.com/jscher2000/Save-webP-as-extension/assets/8264646/41b83082-88ed-4189-814e-43f26a66db75)

**Comment by beefjerky9** [comment]
I'd like to add here that I also had this issue after a fresh install on Firefox. Deleting the prefs did fix the issue, but it doesn't make much sense for this to happen on a new install.

**Comment by jscher2000** [comment]
I found the source of this problem, but I'm not sure why it is occurring. 

When you turn off the automatic bar and save the change, a script runs that unregisters the content script that detects stand-alone pages. That seems to have stopped working in September for some reason (i.e., there was a change in Firefox that I either didn't notice or failed to understand). 

As a fix, I am adding code to check the automatic bar preference a second time. I haven't decided whether to push this tiny change now or wait until I can add some more features.

**Comment by jscher2000** [comment]
I uploaded version 1.4 for review with the bug fix. The main change is a new Copy to Clipboard button.

**Comment by jscher2000** [comment]
Since there haven't been any new reports of this somewhat rare problem, I'll go ahead and close this issue as *probably* fixed.
