### ISSUE TITLE
real stored fileformat

### ISSUE THREAD

**Issue by MlCHEL1234** [jscher2000/Save-webP-as-extension#29]
If you read the description of this addon for Firefox, you will realize that this addon only converts the webp image to jpg and doesn't lownload the original-jpg from the server. So you still have the webp format with its known disadvantages.

However, this is probably not desired by most users.

As a result, the partially high-quality jpg content is increasingly being replaced by the low-quality webp content, almost secretly through the back door. You then only have an image in jpg format, created from a webp and considerably and uselessly inflated during the conversion, because it contains no additional information, or rather, considerably less information than the original.

This addon is therefore completely useless.

As is known, a jpg image is usually always kept on the server (in parallel) and converted to webp on request and then transmitted. Why doesn't this addon bypass this action and download the original jpg? Then this addon would make sense. 

Otherwise it just wastes RAM. With garbage like this you will eventually shut down every computer...

It would be very interesting to hear what the developer has to say on this subject!

Bye, Michael

**Comment by jscher2000** [comment]
Hi Michael, Yes, this extension is a converter. I don't think that is hidden, considering its name on the Add-ons site is "Save webP as PNG or JPEG (Converter)." It works similarly to the built-in screenshot tool, but offers a choice of output formats.

If you want to try to get JPEG from the server, you have a couple options:

1. On this extension's button bar, click the IE button. This will re-request the image masquerading as an old browser.
2. Try my other extension https://addons.mozilla.org/firefox/addon/dont-accept-webp/. Some servers do not care whether the browser says it wants WebP or not, as you can see in the reviews for that extension, so requesting as IE may still be needed with those servers.

I know in the long run I should merge my three image-related extensions, but they work very differently so I'm not looking forward to it.
