### ISSUE TITLE
Colors bug on some sites

### ISSUE THREAD

**Issue by wvxwxvw** [jscher2000/Save-webP-as-extension#3]
Bug-color on some sites. For example on this one. In the addon has a dark theme enabled, but I'm getting colors like this, and can't see anything.  
  
![2021 03 30_034348](https://user-images.githubusercontent.com/13194155/112916931-3fbd4080-910a-11eb-8a72-b5dd370329fe.png)
  
The site is modified with custom css, but I have all frequently visited sites processed with css.  
For example, in this case, using the addon [https://addons.mozilla.org/ru/firefox/addon/darkreader/](url)  
Sometimes I write myself, sometimes I take someone else's ready-made styles.  
  
But I also have several extensions that create their own elements on pages, and I have never seen that the custom css of pages somehow affects the elements of these extensions. So this is clearly a bug on your side. I can assume that it is somehow related to the color fix that is registered in fmtbtns.js 
  
Please let me decide for myself what color of buttons and text I should see, no need for any fixes, let the background always be strictly the same color, the one that is set in light.css and dark.css. I can't fix it myself.

**Comment by jscher2000** [comment]
Thank you for mentioning this problem. Github uses the following rule which changes the background color:

````
button {
  webkit-appearance: button;
}
````

Probably a lot of sites use that. Apparently I need to override it to retain my assigned color.

**Comment by wvxwxvw** [comment]
Thanks. It's great that you found the problem. I will wait for the fix.

**Comment by jscher2000** [comment]
Today's version 1.0 release has a fix for this.

**Comment by wvxwxvw** [comment]
@jscher2000 
Thank you, quick tests showed that the problem was solved.
