### ISSUE TITLE
Addon activating on .png and .gif files

### ISSUE THREAD

**Issue by siffegh** [jscher2000/Save-webP-as-extension#4]
![Screenshot_1](https://user-images.githubusercontent.com/18728013/113064617-59e83480-9185-11eb-9b10-6abb76d3ca23.jpg)

![Screenshot_2](https://user-images.githubusercontent.com/18728013/113064660-6e2c3180-9185-11eb-84c3-212152664a87.jpg)

**Comment by siffegh** [comment]
Win7 Pro SP1/FF 87.0/Save webP as PNG or JPEG 0.9.3

**Comment by siffegh** [comment]
I disabled 'Open bar automatically on stand-alone web images', and that stopped the popup. But why I can still R. click the image and choose to save it as jpg or gif - which it already is?

**Comment by jscher2000** [comment]
Hi, sorry for the delay in responding. There is a checkbox in the Options to control whether it opens automatically, and whether to do it only for webp files.

![options-1B_0 9 4](https://user-images.githubusercontent.com/8264646/113809971-20cc3900-971e-11eb-84f2-40e7d00f97a0.png)

**Comment by siffegh** [comment]
Doh! Yet another senior moment :-/ TY

**Comment by jscher2000** [comment]
That webp-only option is less than a week old, so you're not crazy if you think it wasn't there before.

**Comment by siffegh** [comment]
Nah - I really AM crazy ;-)
