### ISSUE TITLE
Add "AVIF" to the description pages and settings

### ISSUE THREAD

**Issue by anewuser** [jscher2000/Save-webP-as-extension#7]
The extension seems to work fine with [AVIF images](https://libre-software.net/avif-test/) too on Firefox 93. You could mention this on the GitHub and AMO description pages.

Also, consider adding this new format to the `image/webp only` option, or adding a separate checkbox for it.

**Comment by jscher2000** [comment]
Sorry, somehow I missed your first suggestion. I just updated AMO now. https://addons.mozilla.org/firefox/addon/save-webp-as-png-or-jpeg/

I will look at the second issue.

**Comment by jscher2000** [comment]
I just uploaded version 1.1 which combines images/webp and image/avif for the stand-alone option. Let me know whether that works for you.

**Comment by anewuser** [comment]
The bar doesn't load automatically when I use the `Open Image in New Tab` context menu option. Is that a Firefox limitation?

**Comment by jscher2000** [comment]
I noticed that. With the normal behavior of opening the tab in the background, it's not running as expected and I have to reload (Ctrl+R) the page. If the tab is opened as the active tab (checking the box for "When you open a link, image or media in a new tab, switch to it immediately" on the settings page), then the script runs. Sounds like something to work on _next_ weekend...

**Comment by jscher2000** [comment]
It's kind of obvious in retrospect: I needed to expressly tell Firefox where to inject the toolbar script when it wasn't the active tab. Duh. Hopefully fixed in tonight's upload of version 1.2.
