### ISSUE TITLE
[Feature Request] Keep original file name ?

### ISSUE THREAD

**Issue by Elaws** [jscher2000/Save-webP-as-extension#8]
Hi,

When using this extension, files are renamed : is there any way to keep original image name ?

Moreother, it seems that in the options, "Menu Item Options" doesn't allow "save as IE11" shortcut.

Thank you

**Comment by Jiaoriu** [comment]
IE11 Option just saves the file in its original format.

What I would like to see is the simple option to keep the original filename when saving in new file format. I don't need the '_originalformat' addition, I always have to delete it manually - which is very annoying indeed.

**Comment by jscher2000** [comment]
So the current approach is, for example:

* `example.webp` => `example_webp_92.jpg`
* `example.jpg` => `example_jpg_92.jpg`

And the preference for both cases would be:

`example.jpg` 

I think I can do that.

**Comment by Jiaoriu** [comment]
> I think I can do that.

awesome, ty

**Comment by jscher2000** [comment]
I just uploaded version 1.1, which has checkboxes for the old file extension and the JPEG quality number. Let me know whether unchecking those resolves the issue for you.

**Comment by Elaws** [comment]
This is perfect, thank you very much !
